name: Build and Deploy

on:
  push:
    branches: ['master']

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build website
        run: |-
          yarn && yarn build
          curl -Lfo resume.json $GIST
          mkdir -p build/resume
          yarn export build/resume/index.html
          cp LICENSE.txt build
        env:
          GIST: https://gist.githubusercontent.com/ObserverOfTime/c1d5d812134aa2356ee190a741b4e39e/raw/resume.json
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
